"""Added MapCluster table and CLusterNumber on table mapDaa

Revision ID: 1ec7d92faa94
Revises: 292cf251195f
Create Date: 2023-04-17 18:15:14.084589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec7d92faa94'
down_revision = '292cf251195f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_number', sa.Integer(), nullable=False),
    sa.Column('cluster_lat', sa.Float(), nullable=False),
    sa.Column('cluster_long', sa.Float(), nullable=False),
    sa.Column('map_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_data_id'], ['map_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('map_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cluster_number_', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'map_cluster', ['cluster_number_'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cluster_number_')

    op.drop_table('map_cluster')
    # ### end Alembic commands ###
