"""empty message

Revision ID: 292cf251195f
Revises: 
Create Date: 2023-04-06 11:39:04.694602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292cf251195f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('map_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=11), nullable=False),
    sa.Column('id_user_fk', sa.Integer(), nullable=False),
    sa.Column('descrip', sa.String(length=999), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_user_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_data')
    op.drop_table('user')
    # ### end Alembic commands ###
