"""empty message

Revision ID: 3a7d9af6ca69
Revises: 711393de1c30
Create Date: 2022-11-29 22:35:55.976759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7d9af6ca69'
down_revision = '711393de1c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa', schema=None) as batch_op:
        batch_op.alter_column('lat',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('long',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa', schema=None) as batch_op:
        batch_op.alter_column('long',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=0),
               existing_nullable=False)
        batch_op.alter_column('lat',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=0),
               existing_nullable=False)

    # ### end Alembic commands ###
