"""empty message

Revision ID: 711393de1c30
Revises: 
Create Date: 2022-11-29 22:15:00.481328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711393de1c30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mapa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=30), nullable=False),
    sa.Column('lat', sa.Numeric(precision=8, asdecimal=False), nullable=False),
    sa.Column('long', sa.Numeric(precision=8, asdecimal=False), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=250), nullable=True),
    sa.Column('id_user_fk', sa.Integer(), nullable=False),
    sa.Column('descrip', sa.String(length=999), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_user_fk'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapa')
    op.drop_table('user')
    # ### end Alembic commands ###
